### ISSUE TITLE
cp: cannot copy a directory, './var', into itself

### ISSUE THREAD

**Issue by yegor256** [aboutcode-org/scancode-action#10]
This is my YAML config:

```
name: scancode
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scancode:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: aboutcode-org/scancode-action@alpha
        with:
          inputs-path: .
          pipelines: "scan_codebase"
          output-formats: "json xlsx spdx cyclonedx"
```

I'm getting this:

```
cp: cannot copy a directory, './var', into itself, '/home/runner/work/xembly/xembly/var/projects/scancode-action-19c6f344/input/var'
```

Full story is here: https://github.com/yegor256/xembly/actions/runs/13407555080/job/37529053722

**Comment by tdruez** [comment]
@yegor256 you can try the following approach instead of the `.` location:
```
jobs:
  scancode:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
         with:
           path: scancode-inputs
      - uses: aboutcode-org/scancode-action@alpha
        with:
          inputs-path: scancode-inputs
          pipelines: "scan_codebase"
          output-formats: "json xlsx spdx cyclonedx"
```
